In [2]:
z = [1, 2, 3, 4, 5, 6]

In [3]:
z

[1, 2, 3, 4, 5, 6]

In [4]:
x = [6,5,4,3,2,1]

In [5]:
w = 2*z
w

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [6]:
r = w + x
r

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1]

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
b

array([6, 5, 4, 3, 2, 1])

In [11]:
c = 2*a

In [12]:
c

array([ 2,  4,  6,  8, 10, 12])

In [13]:
d = a + b
d

array([7, 7, 7, 7, 7, 7])

In [14]:
print(d)

[7 7 7 7 7 7]


In [15]:
type(c)

numpy.ndarray

In [16]:
d.shape

(6,)

Numpy (Matrices)

In [17]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]  # create a list 
a = np.array(l)  # convert a list to an array 
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [18]:
a.shape

(3, 3)

In [19]:
print(a.dtype)  # get type of an array

int64


In [21]:
M = np.array([[1, 2], [3, 4]])
M.shape

(2, 2)

In [22]:
M.dtype

dtype('int64')

Numpy (Uso de Matrices)

In [23]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [24]:
print(a[0])  # this is just like a list of lists

[1 2 3]


In [25]:
print(a[1, 2])  # arrays can be given comma separated indices

9


In [26]:
print(a[1, 1:3])  # and slices

[6 9]


In [27]:
print(a[:,1])

[2 6 4]


In [28]:
a[1, 2] = 7
print(a)

[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [29]:
a[:, 0] = [0, 9, 8] 
print(a)

[[0 2 3]
 [9 6 7]
 [8 4 6]]


Numpy (Arreglos)

In [30]:
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [34]:
np.logspace(0, 10, 10, base = np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [35]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
b = np.zeros(5) 
print(b)

[0. 0. 0. 0. 0.]


In [37]:
b.dtype

dtype('float64')

In [39]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Numpy  (Arreglos: Creación y uso)

In [40]:
d = np.arange(5)  # just like range() 
>>> print(d)

[0 1 2 3 4]


In [41]:
d[1] = 9.7 
>>> print(d)  # arrays keep their type even if elements changed 

[0 9 2 3 4]


In [42]:
print(d*0.4)  # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [44]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
>>> x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [46]:
# random data
>>> np.random.rand(5,5)

array([[0.28495507, 0.18032593, 0.42006273, 0.91533998, 0.91434093],
       [0.00237478, 0.16437595, 0.63484606, 0.70773784, 0.86482318],
       [0.81238557, 0.85679749, 0.13789251, 0.25124801, 0.69501523],
       [0.27099595, 0.81726277, 0.41529232, 0.55704381, 0.64127902],
       [0.3745762 , 0.56321126, 0.96789354, 0.10926421, 0.04785086]])

Numpy (Creando arreglos)

In [48]:
M = np.random.rand(3,3)
>>> M

array([[0.75854881, 0.23170441, 0.52586155],
       [0.05265754, 0.24778546, 0.05403863],
       [0.03587091, 0.47817695, 0.27503597]])

In [55]:
np.save('saved-matrix.npy', M)


In [56]:
np.load('saved-matrix.npy')

array([[0.75854881, 0.23170441, 0.52586155],
       [0.05265754, 0.24778546, 0.05403863],
       [0.03587091, 0.47817695, 0.27503597]])

In [60]:
a = np.arange(4.0) 
b = a * 23.4 
c = b/(a+1) 
c += 10 
print (c) 

[10.   21.7  25.6  27.55]


In [61]:
arr = np.arange(100, 200) 
select = [5, 25, 50, 75, -5] 
print(arr[select])  # can use integer lists as indices

[105 125 150 175 195]


In [63]:
arr = np.arange(10, 20).reshape((2,5))
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Numpy (Metodos)

In [64]:
arr.sum()

np.int64(145)

In [65]:
arr.mean()

np.float64(14.5)

In [66]:
arr.std()

np.float64(2.8722813232690143)

In [67]:
arr.max()

np.int64(19)

In [68]:
arr.min()

np.int64(10)

Numpy (Metodo sort())

In [69]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5]) 
arr.sort()  # acts on array itself 
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [70]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5]) 
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [71]:
print (x)

[4.5 2.3 6.7 1.2 1.8 5.5]


Numpy (Funciones)

In [74]:
a = np.array([[1.0, 2.0], [4.0, 3.0]]) 
print (a)

[[1. 2.]
 [4. 3.]]


In [75]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [79]:
a = np.array([1,2,3], float) 
b = np.array([5,2,6], float) 
a + b

array([6., 4., 9.])

In [80]:
a - b

array([-4.,  0., -3.])

In [81]:
a * b

array([ 5.,  4., 18.])

In [82]:
b / a

array([5., 1., 2.])

In [83]:
a % b

array([1., 0., 3.])

In [84]:
b**a

array([  5.,   4., 216.])

In [85]:
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
b = np.array([-1, 3], float) 
a 

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [86]:
b

array([-1.,  3.])

In [87]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])